// components/nav-bar.vue
<script setup lang="ts">
const route = useRoute()
const isDark = useDark()

const isSelected = (u: string) => route.path === u
const isExternalLink = (u: string): boolean => {
  try {
    // eslint-disable-next-line no-new
    new URL(u)
    return true
  } catch {
    return false
  }
}

const icon = computed(() =>
  isDark.value
    ? '/default-monochrome-white.svg'
    : '/default-monochrome-black.svg'
)

const LINKS = ref([
  { text: 'About', href: '/' },
  { text: 'Articles', href: '/articles' },
  { text: 'Projects', href: 'https://github.com/threkk/' }
])
</script>
<template>
  <nav class="container">
    <ul>
      <li>
        <NuxtLink to="/">
          <nuxt-img
            format="svg"
            placeholder="/default-monochrome-white.svg"
            :src="icon"
            alt="threkk.com's website logo"
          />
        </NuxtLink>
      </li>
    </ul>
    <label for="menu" tabindex="0">
      <IconCSS name="mdi:hamburger" />
    </label>
    <input id="menu" type="checkbox" :checked="false" />
    <ul>
      <li v-for="link in LINKS" :key="link.href">
        <NuxtLink :to="link.href">
          <strong v-if="isSelected(link.href)">{{ link.text }}</strong>
          <span v-else>{{ link.text }}</span>
          <IconCSS
            v-if="isExternalLink(link.href)"
            name="uil:external-link-alt"
          />
        </NuxtLink>
      </li>
    </ul>
  </nav>
</template>
<style>
/* Placing the logo in the navbar */
nav img {
  height: 2rem;
}

/* Adding some effects to the links */
nav a {
  white-space: nowrap;
}

/* Hamburger menu */
nav input[type='checkbox'],
nav label {
  display: none;
}

@media (max-width: 576px) {
  input[type='checkbox']:not(:checked) + ul {
    display: none;
  }

  nav {
    flex-direction: row;
    flex-wrap: wrap;
    margin-left: 0;
    margin-right: 0;
    padding: calc(var(--form-element-spacing-vertical) * 0.5)
      var(--form-element-spacing-horizontal);
  }

  nav label {
    text-align: right;
    display: block;
    font-size: 2rem;
    line-height: 1.3em;
  }

  nav ul {
    display: block;
  }

  nav ul:last-child {
    width: 100%;
    flex-basis: 100%;
  }

  nav ul li {
    margin-bottom: 0;
    width: 100%;
    text-align: right;
    padding: calc(var(--form-element-spacing-vertical) * 0.5)
      var(--form-element-spacing-horizontal);
  }
}
</style>

// components/Navbar.tsx
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import { useDarkMode } from '../lib/useDarkMode'
import LogoLight from '../public/default-monochrome-black.svg'
import LogoDark from '../public/default-monochrome-white.svg'

type MenuItem = {
  text: string
  href: string
  disabled?: boolean
}

const LINKS: MenuItem[] = [
  { text: 'About', href: '/' },
  { text: 'Projects', href: 'https://github.com/threkk/' },
  { text: 'Articles', href: '/articles' },
  {
    text: 'Now',
    href: 'https://www.notion.so/threkk/Now-f120106f4eea4f6895589f061cb548ad'
  }
]

const ExternalLink = (
  <i
    className='fa-solid fa-external-link-alt'
    style={{ opacity: 0.3, userSelect: 'none', marginLeft: '0.3rem' }}
  ></i>
)

function isExternalLink(u: string): boolean {
  try {
    // eslint-disable-next-line no-new
    new URL(u)
    return true
  } catch {
    return false
  }
}

export default function Navbar() {
  const router = useRouter()
  const isDarkMode = useDarkMode()
  const isSelected = (page: MenuItem) => router.pathname === page.href

  const Logo = isDarkMode ? LogoDark : LogoLight

  const links = LINKS.map((page) => (
    <li key={page.href}>
      <Link key={page.text} href={page.href} style={{ whiteSpace: 'nowrap' }}>
          {isSelected(page) ? <strong>{page.text}</strong> : page.text}
          {isExternalLink(page.href) ? ExternalLink : ''}
      </Link>
    </li>
  ))

  return (
    <>
      <nav>
        <ul>
          <li>
            <Link href='https://threkk.com'>
                <Image
                  src={Logo}
                  alt="threkk.com's website logo"
                  priority={true}
                  style={{
                    width: 'auto',
                    height: '2rem'
                  }}
                />
            </Link>
          </li>
        </ul>
        <label htmlFor='menu' tabIndex={0}>
          <i className='fa-solid fa-2x fa-burger'></i>
        </label>
        <input id='menu' type='checkbox' defaultChecked={false} />
        <ul>{links}</ul>
      </nav>
    </>
  )
}
